[package]
name = "reporch-runtime-core"
version = "1.0.0-rc.9"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
chrono.workspace = true
reporch-runtime-protocol = { path = "../reporch-runtime-protocol" }
serde.workspace = true
thiserror.workspace = true
url.workspace = true
