[package]
name = "reporch-runtime-source-fetcher"
version = "1.0.0-rc.11"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
cab.workspace = true
flate2.workspace = true
futures-util.workspace = true
hex.workspace = true
msi.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tar.workspace = true
tokio.workspace = true
url.workspace = true
uuid.workspace = true

[target.'cfg(not(windows))'.dependencies]
reqwest = { workspace = true, features = ["rustls"] }

[target.'cfg(windows)'.dependencies]
reqwest = { workspace = true, features = ["native-tls"] }

[dev-dependencies]
tempfile.workspace = true
