// QA regression: CLI-090-003.
// Generated by Codex on 2026-08-14 after the 0.9 production command-surface audit.

use std::fs;
use std::process::{Command, Output};

use reporch_cli::authoring_runtime::standard_checker_matches;
use serde_json::Value;
use studio_core::CheckerSpec;

fn reporch() -> Command {
    Command::new(env!("CARGO_BIN_EXE_reporch"))
}

fn init(directory: &std::path::Path, problem_type: Option<&str>) {
    let mut command = reporch();
    command.args([
        "--quiet",
        "project",
        "init",
        "--title",
        "Authoring regression",
        "--directory",
        directory.to_str().unwrap(),
    ]);
    if let Some(problem_type) = problem_type {
        command.args(["--problem-type", problem_type]);
    }
    let output = command.output().unwrap();
    assert!(output.status.success(), "{output:?}");
}

fn run_json(directory: &std::path::Path, arguments: &[&str]) -> Output {
    reporch()
        .args(["--cwd", directory.to_str().unwrap(), "--format", "json"])
        .args(arguments)
        .output()
        .unwrap()
}

fn assert_help_commands(family: &str, expected: &[&str]) {
    let output = reporch().args([family, "--help"]).output().unwrap();
    assert!(output.status.success(), "{family}: {output:?}");
    assert!(output.stderr.is_empty(), "{family}: {output:?}");
    let help = String::from_utf8(output.stdout).unwrap();
    for expected in expected {
        assert!(
            help.lines().any(|line| {
                let line = line.trim_start();
                line == *expected
                    || line
                        .strip_prefix(expected)
                        .and_then(|suffix| suffix.chars().next())
                        .is_some_and(char::is_whitespace)
            }),
            "missing {family} {expected}:\n{help}"
        );
    }
}

#[test]
fn every_promised_expert_authoring_command_is_reachable_without_a_clap_panic() {
    for (family, commands) in [
        ("statement", &["add", "open", "check", "render"][..]),
        ("generator", &["list", "add", "recipe", "run", "remove"][..]),
        ("validator", &["set", "unit-add", "run"][..]),
        ("checker", &["list-standard", "set", "unit-add", "run"][..]),
        (
            "solution",
            &["list", "add", "update", "remove", "matrix"][..],
        ),
        ("answer", &["generate"][..]),
        ("stress", &["list", "add", "run", "remove"][..]),
        ("interactor", &["set", "run", "transcript"][..]),
        ("grader", &["set", "run"][..]),
        ("output", &["list", "add", "remove", "test"][..]),
    ] {
        assert_help_commands(family, commands);
    }
}

#[test]
fn renderer_and_standard_checker_flows_are_deterministic_safe_and_non_overwriting() {
    let standard = tempfile::tempdir().unwrap();
    init(standard.path(), None);
    fs::write(
        standard.path().join("statements/ko.md"),
        "# Safe\n\n1 < 2\n",
    )
    .unwrap();
    let rendered = run_json(
        standard.path(),
        &[
            "statement",
            "render",
            "--locale",
            "ko",
            "--render-format",
            "html",
            "--output",
            "rendered/ko.html",
        ],
    );
    assert!(rendered.status.success(), "{rendered:?}");
    let html = fs::read_to_string(standard.path().join("rendered/ko.html")).unwrap();
    assert!(html.contains("Content-Security-Policy"), "{html}");
    assert!(html.contains("1 &lt; 2"), "{html}");

    let overwrite = run_json(
        standard.path(),
        &[
            "statement",
            "render",
            "--locale",
            "ko",
            "--output",
            "rendered/ko.html",
        ],
    );
    assert_eq!(overwrite.status.code(), Some(2), "{overwrite:?}");
    assert_eq!(
        fs::read_to_string(standard.path().join("rendered/ko.html")).unwrap(),
        html
    );

    fs::write(
        standard.path().join("statements/ko.md"),
        "[unsafe](javascript:alert(1))\n",
    )
    .unwrap();
    let unsafe_render = run_json(
        standard.path(),
        &[
            "statement",
            "render",
            "--locale",
            "ko",
            "--render-format",
            "html",
        ],
    );
    assert_eq!(unsafe_render.status.code(), Some(2), "{unsafe_render:?}");
    fs::write(standard.path().join("statements/ko.md"), "# Safe\n").unwrap();

    let unit = run_json(
        standard.path(),
        &[
            "checker",
            "unit-add",
            "--name",
            "accepted",
            "--input",
            "tests/1.in",
            "--answer",
            "tests/1.ans",
            "--output",
            "tests/1.ans",
            "--expected",
            "accept",
        ],
    );
    assert!(unit.status.success(), "{unit:?}");
    let checked = run_json(standard.path(), &["checker", "run"]);
    assert!(checked.status.success(), "{checked:?}");

    assert!(standard_checker_matches(&CheckerSpec::Token, b"1  2\n", b"1\n2 ").unwrap());
    assert!(standard_checker_matches(&CheckerSpec::CaseInsensitive, b"Yes NO", b"yes no").unwrap());
    assert!(
        standard_checker_matches(
            &CheckerSpec::Floating {
                absolute_error: "0.001".into(),
                relative_error: "0.0001".into(),
            },
            b"10.0",
            b"10.0005",
        )
        .unwrap()
    );

    let output_only = tempfile::tempdir().unwrap();
    init(output_only.path(), Some("output-only"));
    let tested = run_json(output_only.path(), &["output", "test"]);
    assert!(tested.status.success(), "{tested:?}");
    let envelope: Value = serde_json::from_slice(&tested.stdout).unwrap();
    assert_eq!(envelope["command"], "output test");
    assert_eq!(envelope["data"]["passed"], true);
    assert_eq!(envelope["data"]["submissions"][0]["score"], 100.0);
    assert_eq!(envelope["data"]["submissions"][1]["score"], 0.0);
}

#[cfg(unix)]
#[test]
fn statement_operations_reject_symlinks_outside_the_project() {
    use std::os::unix::fs::symlink;

    let project = tempfile::tempdir().unwrap();
    let outside = tempfile::NamedTempFile::new().unwrap();
    fs::write(outside.path(), "# outside\n").unwrap();
    init(project.path(), None);
    let statement = project.path().join("statements/ko.md");
    fs::remove_file(&statement).unwrap();
    symlink(outside.path(), &statement).unwrap();

    for arguments in [
        vec!["statement", "check"],
        vec!["statement", "render", "--locale", "ko"],
    ] {
        let output = run_json(project.path(), &arguments);
        assert_eq!(output.status.code(), Some(2), "{output:?}");
        assert!(
            String::from_utf8_lossy(&output.stderr).contains("non-symlink"),
            "{output:?}"
        );
    }
}

#[test]
fn v2_projects_can_edit_statements_tests_and_named_groups_without_internal_ids() {
    let project = tempfile::tempdir().unwrap();
    init(project.path(), None);
    reporch_cli::local_project_v2::migrate_v1_authoring_file(project.path()).unwrap();

    let checked = run_json(project.path(), &["statement", "check"]);
    assert!(checked.status.success(), "{checked:?}");
    let group = run_json(
        project.path(),
        &["test", "group", "add", "easy", "--points", "100"],
    );
    assert!(group.status.success(), "{group:?}");
    let added = run_json(
        project.path(),
        &[
            "test",
            "case",
            "add",
            "--name",
            "second",
            "--input",
            "tests/1.in",
            "--answer",
            "tests/1.ans",
            "--group",
            "easy",
        ],
    );
    assert!(added.status.success(), "{added:?}");

    let spec = reporch_cli::local_project_v2::read_authoring_spec(project.path()).unwrap();
    let easy = spec
        .testing
        .groups
        .iter()
        .find(|group| group.name == "easy")
        .unwrap();
    let second = spec
        .testing
        .tests
        .iter()
        .find(|test| test.name == "second")
        .unwrap();
    assert_eq!(second.group_ids, vec![easy.id]);
    let checked = run_json(project.path(), &["check"]);
    assert!(checked.status.success(), "{checked:?}");
    let checked: Value = serde_json::from_slice(&checked.stdout).unwrap();
    assert_eq!(
        checked["data"]["authoring_schema"],
        "reporch.authoring-spec.v2"
    );
    let status = run_json(project.path(), &["project", "status"]);
    assert!(status.status.success(), "{status:?}");
    let diff = run_json(project.path(), &["project", "diff"]);
    assert!(diff.status.success(), "{diff:?}");
}

#[cfg(unix)]
fn fake_rootless_runtime(directory: &std::path::Path) -> std::path::PathBuf {
    use std::os::unix::fs::PermissionsExt as _;

    let path = directory.join("podman");
    fs::write(
        &path,
        r#"#!/bin/sh
set -eu
case "$1" in
  --version)
    printf '%s\n' 'podman version 5.0.0'
    ;;
  info)
    printf '%s\n' '{"host":{"security":{"rootless":true}}}'
    ;;
  image)
    last=''
    for argument in "$@"; do last=$argument; done
    printf '["%s"]\n' "$last"
    ;;
  run)
    if [ -n "${REPORCH_FAKE_LOG:-}" ]; then
      for argument in "$@"; do printf 'ARG=%s\n' "$argument" >> "$REPORCH_FAKE_LOG"; done
    fi
    output="${REPORCH_FAKE_STDOUT:-}"
    if [ "${REPORCH_FAKE_SCENARIO:-}" = stress ]; then
      joined=" $* "
      case "$joined" in
        *'/workspace/generators/stress.py'*) output='1 2\n' ;;
        *'/workspace/solutions/wrong.py'*) output='0\n' ;;
        *'/workspace/solutions/accepted.py'*) output='3\n' ;;
      esac
    fi
    printf '%b' "$output"
    exit "${REPORCH_FAKE_EXIT:-0}"
    ;;
  rm)
    ;;
  *)
    exit 64
    ;;
esac
"#,
    )
    .unwrap();
    fs::set_permissions(&path, fs::Permissions::from_mode(0o755)).unwrap();
    path
}

#[cfg(unix)]
fn fake_runtime_command(
    runtime_directory: &std::path::Path,
    project: &std::path::Path,
    arguments: &[&str],
    stdout: &str,
    log: &std::path::Path,
) -> Output {
    let inherited_path = std::env::var_os("PATH").unwrap_or_default();
    let mut paths = vec![runtime_directory.to_owned()];
    paths.extend(std::env::split_paths(&inherited_path));
    let path = std::env::join_paths(paths).unwrap();
    reporch()
        .args(["--cwd", project.to_str().unwrap(), "--format", "json"])
        .args(arguments)
        .env("PATH", path)
        .env("REPORCH_FAKE_STDOUT", stdout)
        .env("REPORCH_FAKE_LOG", log)
        .output()
        .unwrap()
}

#[cfg(unix)]
fn fake_stress_command(
    runtime_directory: &std::path::Path,
    project: &std::path::Path,
    arguments: &[&str],
    log: &std::path::Path,
) -> Output {
    let inherited_path = std::env::var_os("PATH").unwrap_or_default();
    let mut paths = vec![runtime_directory.to_owned()];
    paths.extend(std::env::split_paths(&inherited_path));
    let path = std::env::join_paths(paths).unwrap();
    reporch()
        .args(["--cwd", project.to_str().unwrap(), "--format", "json"])
        .args(arguments)
        .env("PATH", path)
        .env("REPORCH_FAKE_SCENARIO", "stress")
        .env("REPORCH_FAKE_LOG", log)
        .output()
        .unwrap()
}

#[cfg(unix)]
#[test]
fn signed_rootless_execution_wires_generators_validators_checkers_interactors_and_graders() {
    let runtime = tempfile::tempdir().unwrap();
    fake_rootless_runtime(runtime.path());
    let log = runtime.path().join("arguments.log");

    let standard = tempfile::tempdir().unwrap();
    init(standard.path(), None);
    let added = run_json(
        standard.path(),
        &[
            "generator",
            "add",
            "--id",
            "gen",
            "--source",
            "solutions/accepted.py",
            "--language",
            "python3",
        ],
    );
    assert!(added.status.success(), "{added:?}");
    let hostile = "$(touch /workspace/owned);`id`";
    let generated = fake_runtime_command(
        runtime.path(),
        standard.path(),
        &[
            "generator",
            "run",
            "gen",
            "--output",
            "tests/generated.in",
            "--name",
            "generated",
            "--seed",
            "7",
            "--argument",
            hostile,
            "--runtime",
            "podman",
        ],
        "5\n",
        &log,
    );
    assert!(generated.status.success(), "{generated:?}");
    assert_eq!(
        fs::read(standard.path().join("tests/generated.in")).unwrap(),
        b"5\n"
    );
    assert!(!standard.path().join("owned").exists());
    let log_contents = fs::read_to_string(&log).unwrap();
    assert_eq!(
        log_contents
            .lines()
            .filter(|line| *line == format!("ARG={hostile}"))
            .count(),
        2,
        "fixed-seed generation must execute twice with the hostile value only as an argv entry:\n{log_contents}"
    );

    assert!(
        run_json(
            standard.path(),
            &[
                "validator",
                "set",
                "--source",
                "solutions/accepted.py",
                "--language",
                "python3",
            ],
        )
        .status
        .success()
    );
    assert!(
        run_json(
            standard.path(),
            &[
                "validator",
                "unit-add",
                "--name",
                "valid",
                "--input",
                "tests/1.in",
                "--expected",
                "valid",
            ],
        )
        .status
        .success()
    );
    let validator = fake_runtime_command(
        runtime.path(),
        standard.path(),
        &["validator", "run", "--runtime", "podman"],
        "",
        &log,
    );
    assert!(validator.status.success(), "{validator:?}");

    let interactive = tempfile::tempdir().unwrap();
    init(interactive.path(), Some("interactive"));
    let interactive_spec =
        reporch_cli::local_project_v2::read_authoring_spec(interactive.path()).unwrap();
    let test_id = interactive_spec.testing.tests[0].id.to_string();
    let transcript = fake_runtime_command(
        runtime.path(),
        interactive.path(),
        &[
            "interactor",
            "transcript",
            "--solution",
            "accepted",
            "--test",
            &test_id,
            "--runtime",
            "podman",
        ],
        "solver -> interactor\n",
        &log,
    );
    assert!(transcript.status.success(), "{transcript:?}");

    let grader = tempfile::tempdir().unwrap();
    init(grader.path(), Some("grader"));
    let grader_spec = reporch_cli::local_project_v2::read_authoring_spec(grader.path()).unwrap();
    let grader_test_id = grader_spec.testing.tests[0].id.to_string();
    let graded = fake_runtime_command(
        runtime.path(),
        grader.path(),
        &[
            "grader",
            "run",
            "--solution",
            "accepted",
            "--test",
            &grader_test_id,
            "--runtime",
            "podman",
        ],
        "3\n",
        &log,
    );
    assert!(graded.status.success(), "{graded:?}");
}

#[cfg(unix)]
#[test]
fn v2_answer_generation_and_stress_suite_configuration_are_persisted() {
    let runtime = tempfile::tempdir().unwrap();
    fake_rootless_runtime(runtime.path());
    let log = runtime.path().join("answer-stress.log");
    let project = tempfile::tempdir().unwrap();
    init(project.path(), None);

    fs::write(project.path().join("tests/answerless.in"), b"1 2\n").unwrap();
    let added = run_json(
        project.path(),
        &[
            "test",
            "case",
            "add",
            "--name",
            "answerless",
            "--input",
            "tests/answerless.in",
        ],
    );
    assert!(added.status.success(), "{added:?}");
    let answer = fake_runtime_command(
        runtime.path(),
        project.path(),
        &[
            "answer",
            "generate",
            "--solution",
            "accepted",
            "--runtime",
            "podman",
            "--missing-only",
        ],
        "3\n",
        &log,
    );
    assert!(answer.status.success(), "{answer:?}");
    assert_eq!(
        fs::read(project.path().join("tests/answerless.ans")).unwrap(),
        b"3\n"
    );

    fs::create_dir_all(project.path().join("generators")).unwrap();
    fs::write(
        project.path().join("generators/stress.py"),
        b"# generator\n",
    )
    .unwrap();
    let generator = run_json(
        project.path(),
        &[
            "generator",
            "add",
            "--id",
            "stress-gen",
            "--source",
            "generators/stress.py",
            "--language",
            "python3",
        ],
    );
    assert!(generator.status.success(), "{generator:?}");
    let generated = fake_runtime_command(
        runtime.path(),
        project.path(),
        &[
            "generator",
            "run",
            "stress-gen",
            "--output",
            "tests/stress-seed.in",
            "--name",
            "stress-seed",
            "--seed",
            "11",
            "--runtime",
            "podman",
        ],
        "7 8\n",
        &log,
    );
    assert!(generated.status.success(), "{generated:?}");
    let stress = run_json(
        project.path(),
        &[
            "stress",
            "add",
            "--name",
            "known-wrong-check",
            "--generator",
            "stress-gen",
            "--recipe",
            "case-stress-seed",
            "--oracle",
            "accepted",
            "--candidate",
            "known-wrong",
            "--cases",
            "5",
        ],
    );
    assert!(stress.status.success(), "{stress:?}");
    let spec = reporch_cli::local_project_v2::read_authoring_spec(project.path()).unwrap();
    assert_eq!(spec.testing.stress_suites.len(), 1);
    assert_eq!(spec.testing.stress_suites[0].cases, 5);
    let stressed = fake_stress_command(
        runtime.path(),
        project.path(),
        &["stress", "run", "known-wrong-check", "--runtime", "podman"],
        &log,
    );
    assert!(stressed.status.success(), "{stressed:?}");
    let report: Value = serde_json::from_slice(&stressed.stdout).unwrap();
    assert_eq!(report["data"][0]["passed"], true);
    assert_eq!(report["data"][0]["counterexample_seed"], 1);
    assert!(
        project
            .path()
            .join("stress-failures/known-wrong-check-1.in")
            .is_file()
    );
}

#[cfg(unix)]
#[test]
fn v2_generator_materialization_persists_a_replayable_recipe_and_seed() {
    let runtime = tempfile::tempdir().unwrap();
    fake_rootless_runtime(runtime.path());
    let log = runtime.path().join("v2-generator.log");
    let project = tempfile::tempdir().unwrap();
    init(project.path(), None);
    reporch_cli::local_project_v2::migrate_v1_authoring_file(project.path()).unwrap();

    let added = run_json(
        project.path(),
        &[
            "generator",
            "add",
            "--id",
            "gen",
            "--source",
            "solutions/accepted.py",
            "--language",
            "python3",
        ],
    );
    assert!(added.status.success(), "{added:?}");
    let generated = fake_runtime_command(
        runtime.path(),
        project.path(),
        &[
            "generator",
            "run",
            "gen",
            "--output",
            "tests/v2-generated.in",
            "--name",
            "generated-v2",
            "--seed",
            "17",
            "--runtime",
            "podman",
        ],
        "17\n",
        &log,
    );
    assert!(generated.status.success(), "{generated:?}");
    let spec = reporch_cli::local_project_v2::read_authoring_spec(project.path()).unwrap();
    let generator = spec
        .testing
        .generators
        .iter()
        .find(|generator| generator.program.name == "gen")
        .unwrap();
    let test = spec
        .testing
        .tests
        .iter()
        .find(|test| test.name == "generated-v2")
        .unwrap();
    let generated = test.generated.as_ref().unwrap();
    assert_eq!(generated.generator_id, generator.program.id);
    assert_eq!(generated.seed, 17);
    assert_eq!(generator.recipes[0].id, generated.recipe_id);
    assert_eq!(
        fs::read(project.path().join(&test.input_file)).unwrap(),
        b"17\n"
    );
}

#[cfg(unix)]
#[test]
fn v2_validator_checker_and_solution_flows_execute_and_persist() {
    let runtime = tempfile::tempdir().unwrap();
    fake_rootless_runtime(runtime.path());
    let log = runtime.path().join("v2-programs.log");
    let project = tempfile::tempdir().unwrap();
    init(project.path(), None);
    reporch_cli::local_project_v2::migrate_v1_authoring_file(project.path()).unwrap();

    assert!(
        run_json(
            project.path(),
            &[
                "validator",
                "set",
                "--source",
                "solutions/accepted.py",
                "--language",
                "python3",
            ],
        )
        .status
        .success()
    );
    assert!(
        run_json(
            project.path(),
            &[
                "validator",
                "unit-add",
                "--name",
                "valid-v2",
                "--input",
                "tests/1.in",
                "--expected",
                "valid",
            ],
        )
        .status
        .success()
    );
    let validated = fake_runtime_command(
        runtime.path(),
        project.path(),
        &["validator", "run", "--runtime", "podman"],
        "",
        &log,
    );
    assert!(validated.status.success(), "{validated:?}");

    assert!(
        run_json(
            project.path(),
            &[
                "checker",
                "unit-add",
                "--name",
                "accept-v2",
                "--input",
                "tests/1.in",
                "--answer",
                "tests/1.ans",
                "--output",
                "tests/1.ans",
                "--expected",
                "accept",
            ],
        )
        .status
        .success()
    );
    let checked = run_json(project.path(), &["checker", "run"]);
    assert!(checked.status.success(), "{checked:?}");

    let added = run_json(
        project.path(),
        &[
            "solution",
            "add",
            "--name",
            "third-accepted",
            "--source",
            "solutions/accepted.py",
            "--language",
            "python3",
            "--expected",
            "accepted",
        ],
    );
    assert!(added.status.success(), "{added:?}");
    let matrix = run_json(project.path(), &["solution", "matrix"]);
    assert!(matrix.status.success(), "{matrix:?}");
    let spec = reporch_cli::local_project_v2::read_authoring_spec(project.path()).unwrap();
    assert!(spec.testing.validators.primary.is_some());
    assert_eq!(spec.testing.validators.unit_tests.len(), 1);
    assert_eq!(spec.testing.checker.unit_tests.len(), 1);
    assert!(
        spec.testing
            .solutions
            .iter()
            .any(|solution| solution.program.name == "third-accepted")
    );
}

#[cfg(unix)]
#[test]
fn v2_interactive_grader_and_output_only_flows_match_expected_verdicts() {
    let runtime = tempfile::tempdir().unwrap();
    fake_rootless_runtime(runtime.path());
    let log = runtime.path().join("v2-specialized.log");

    let interactive = tempfile::tempdir().unwrap();
    init(interactive.path(), Some("interactive"));
    reporch_cli::local_project_v2::migrate_v1_authoring_file(interactive.path()).unwrap();
    let interactive_spec =
        reporch_cli::local_project_v2::read_authoring_spec(interactive.path()).unwrap();
    let interactive_test = interactive_spec.testing.tests[0].id.to_string();
    let transcript = fake_runtime_command(
        runtime.path(),
        interactive.path(),
        &[
            "interactor",
            "transcript",
            "--solution",
            "accepted",
            "--test",
            &interactive_test,
            "--runtime",
            "podman",
        ],
        "solver -> interactor\n",
        &log,
    );
    assert!(transcript.status.success(), "{transcript:?}");

    let grader = tempfile::tempdir().unwrap();
    init(grader.path(), Some("grader"));
    reporch_cli::local_project_v2::migrate_v1_authoring_file(grader.path()).unwrap();
    let configured = run_json(
        grader.path(),
        &[
            "grader",
            "set",
            "--source",
            "cpp/grader.cpp",
            "--language",
            "cpp",
        ],
    );
    assert!(configured.status.success(), "{configured:?}");
    let grader_spec = reporch_cli::local_project_v2::read_authoring_spec(grader.path()).unwrap();
    let grader_profile = &grader_spec.execution.harness.as_ref().unwrap().profiles["cpp"];
    assert_eq!(grader_profile.source_path, "cpp/grader.cpp");
    assert_eq!(
        grader_profile.submission_source_path.as_deref(),
        Some("cpp/solution.cpp")
    );
    assert_eq!(
        grader_profile.compile_script.as_deref(),
        Some("cpp/compile.sh")
    );
    assert_eq!(grader_profile.run_script.as_deref(), Some("cpp/run.sh"));
    let grader_test = grader_spec.testing.tests[0].id.to_string();
    let graded = fake_runtime_command(
        runtime.path(),
        grader.path(),
        &[
            "grader",
            "run",
            "--solution",
            "accepted",
            "--test",
            &grader_test,
            "--runtime",
            "podman",
        ],
        "3\n",
        &log,
    );
    assert!(graded.status.success(), "{graded:?}");

    let output_only = tempfile::tempdir().unwrap();
    init(output_only.path(), Some("output-only"));
    reporch_cli::local_project_v2::migrate_v1_authoring_file(output_only.path()).unwrap();
    let tested = run_json(output_only.path(), &["output", "test"]);
    assert!(tested.status.success(), "{tested:?}");
    let envelope: Value = serde_json::from_slice(&tested.stdout).unwrap();
    assert_eq!(envelope["data"]["passed"], true);
}

#[test]
fn grader_set_can_build_a_complete_profile_without_ambiguous_source_roles() {
    let project = tempfile::tempdir().unwrap();
    init(project.path(), Some("grader"));
    reporch_cli::local_project_v2::migrate_v1_authoring_file(project.path()).unwrap();
    fs::create_dir_all(project.path().join("c")).unwrap();
    fs::write(
        project.path().join("c/grader.c"),
        b"int grade(void){return 0;}\n",
    )
    .unwrap();
    fs::write(
        project.path().join("c/solution.c"),
        b"int solve(void){return 0;}\n",
    )
    .unwrap();
    fs::write(project.path().join("c/compile.sh"), b"#!/bin/sh\nexit 0\n").unwrap();
    fs::write(project.path().join("c/run.sh"), b"#!/bin/sh\nexit 0\n").unwrap();

    let configured = run_json(
        project.path(),
        &[
            "grader",
            "set",
            "--source",
            "c/grader.c",
            "--language",
            "c",
            "--submission-template",
            "c/solution.c",
            "--compile-script",
            "c/compile.sh",
            "--run-script",
            "c/run.sh",
        ],
    );
    assert!(configured.status.success(), "{configured:?}");

    let spec = reporch_cli::local_project_v2::read_authoring_spec(project.path()).unwrap();
    let harness = spec.execution.harness.unwrap();
    let profile = &harness.profiles["c"];
    assert_eq!(profile.source_path, "c/grader.c");
    assert_eq!(
        profile.submission_source_path.as_deref(),
        Some("c/solution.c")
    );
    assert!(harness.private_files.contains(&"c/grader.c".into()));
    assert!(profile.asset_paths.contains(&"c/solution.c".into()));
    assert!(profile.asset_paths.contains(&"c/grader.c".into()));
    assert!(run_json(project.path(), &["check"]).status.success());
}
